kiss_icp_node:
  ros__parameters:
    data:
      deskew: true
      max_range: 100.0
      min_range: 0.5

    mapping:
      voxel_size: 0.5
      max_points_per_voxel: 50

    adaptive_threshold:
      initial_threshold: 2.0
      min_motion_th: 0.1

    registration:
      max_num_iterations: 500
      convergence_criterion: 0.0001
